# Preparing the Dataset for BERTopic

In [1]:
# Import libraries
import os
import pandas as pd
# Import dataset that was created in Step 1
#df = pd.read_csv("dpdr_preprocessed.csv")
df = pd.read_csv("dpdr_preprocessed_final.csv")


len(df)

922

In [3]:
# Which Python Version am I using?
import sys

print(sys.version)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [2]:
#Which version is being used?
import bertopic
print("BERTopic Version:",bertopic.__version__)

BERTopic Version: 0.17.4

In [4]:
# Create a list for BERTopic
docs = df["document"].tolist()
# Did it work?
docs[0]

"Am I too inteligent for life or am i just coping? 've constructed a fake world in my mind, the real world became a second priority. My fake world is unexplainable to others, but it offers me comfort while the real world seems like hell, even though my life isn't especially traumatic, I'm just extremely lonely, with not a single soul to talk to besides my therapist of one month (this experience of somebody listending to me has been extremely validating, and I'm able to understand myself a little bit more).I've been sufferering from a derealization so bad that I didn't even think people were real, even my parents whom I avoided. They all just seemed like NPC and i couldn't comprehend the idea that they also have thoughts and their own life.I don't know whether I'm just too smart for life or it's the fact that I've been neglected emotionally by parents (idk if its real, found out this week on reddit, but it explains why I've always wanted to leave home).Does anybody relate?"

In [5]:
# Does the decoding work?
print(df["document"].str.contains(r"Ã|â|�", na=False).sum())
#Yes, it does

0

# BERTopic

Create the Vectoriser

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    stop_words="english",#Either this or the custom list
    ngram_range=(1, 2),
    min_df=8,
    max_df=0.95,
)
# stop_words=english -> English stop word list
#ngram_range -> allows for 2 words instead of 1 in the vector
#min_df=5 -> A word must appear in at least 8 documents to be included
#max_df=0.5 -> A word can only appear in max 70% of documents, otherwise it will be excluded (only affects topic labels, not clustering, i.e. only affects final keyword representation, not how documents are grouped)

Create the c-TF-IDF transformer

In [8]:
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
#After clustering documents into topics, BERTopic needs to identify the key words for each topic.
#reduce_frequent_words=True -> downweights words that appear in many topics.

In [9]:
from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")  # already used implicitly
umap_model = UMAP(n_neighbors=13, n_components=5, min_dist=0.0, metric='cosine', random_state=42)#for old dataset: n_neighbors=5, for new: =10; n_neighbors drastically influences number of topics
hdbscan_model = HDBSCAN(min_cluster_size=13, min_samples=4, metric='euclidean', prediction_data=True) #lower min_samples = fewer outliers; min_samples currently 4 (best balance between having many outliers and insensible topics

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Create the BERTopic Model

In [10]:
from bertopic import BERTopic

topic_model = BERTopic(
    #top_n_words=10, #not in old dataset; the more words you put in a topic the less coherent it can become (keep between 10 and 20)
    min_topic_size=20,   # lower = more topics, 20 in original dataset, adjust when needed
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    nr_topics="auto", # "auto" automatically tries to reduce topic size
    calculate_probabilities=True,
    verbose=True
)

Train the Model

In [11]:
topics, probs = topic_model.fit_transform(docs)

2026-08-30 18:06:46,269 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

2026-08-30 18:07:43,748 - BERTopic - Embedding - Completed ✓
2026-08-30 18:07:43,753 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-30 18:08:05,259 - BERTopic - Dimensionality - Completed ✓
2026-08-30 18:08:05,261 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-30 18:08:05,522 - BERTopic - Cluster - Completed ✓
2026-08-30 18:08:05,528 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-08-30 18:08:06,044 - BERTopic - Representation - Completed ✓
2026-08-30 18:08:06,046 - BERTopic - Topic reduction - Reducing number of topics
2026-08-30 18:08:06,073 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-30 18:08:06,593 - BERTopic - Representation - Completed ✓
2026-08-30 18:08:06,598 - BERTopic - Topic reduction - Reduced number of topics from 15 to 15

In [6]:
# What does the model look like?
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,283,-1_dream_reality_low_ocd,Outliers,"[dream, reality, low, ocd, feels like, right, ...",NaN
1,0,87,0_weed_high_started_pretty,Substance Use,"[weed, high, started, pretty, went, school, ag...",NaN
2,1,84,1_like im_sleep_panic_attack,Panic & Health Anxiety,"[like im, sleep, panic, attack, panic attack, ...",NaN
3,2,60,2_therapy_post_finally_enjoy,Therapeutic & Social Support,"[therapy, post, finally, enjoy, friends, schoo...",NaN
4,3,60,3_memory_memories_remember_self,Discussing Symptoms #1,"[memory, memories, remember, self, reality, dr...",NaN
5,4,50,4_tried_supplements_medication_helps,Treatment,"[tried, supplements, medication, helps, taking...",NaN
6,5,46,5_room_study_research_open,Discussing Symptoms #2,"[room, study, research, open, link, awareness,...",NaN
7,6,45,6_pressure_head_breathing_happen,Physical & Sensory Symptoms,"[pressure, head, breathing, happen, weird, sma...",NaN
8,7,40,7_sub_posts_life felt_felt like,Living with DPDR,"[sub, posts, life felt, felt like, know dpdr, ...",NaN
9,8,38,8_blank_human_want_don know,Hopelessness,"[blank, human, want, don know, lost, happy, re...",NaN
10,9,35,9_conscious_inside_seeing_trapped,Discussing Symptoms #3,"[conscious, inside, seeing, trapped, talking, ...",NaN
11,10,34,10_existential_death_ocd_believe,Existential Concerns,"[existential, death, ocd, believe, exist, true...",NaN
12,11,27,11_derealization_dreaming_depersonalization_de...,Diverse (Causes & Symptom Fluctuation),"[derealization, dreaming, depersonalization, d...",NaN
13,12,19,12_dose_panic_effects_psychiatrist,Medication Experiences,"[dose, panic, effects, psychiatrist, worsening...",NaN
14,13,14,13_trust_getting worse_mild_physical,Diverse (Symptoms & Recovery),"[trust, getting worse, mild, physical, work, w...",NaN

Let's inspect the topics further

In [7]:
#topic_model
#topic_info = topic_model.get_topic_info()
#topic_info
#topic_info.head(7)

#Try to show complete 'representation' column
with pd.option_context('display.max_colwidth', None):
    display(topic_model.get_topic_info()[['Topic', 'Count', 'Representation']])

,Topic,Count,Representation
0,-1,283,"[dream, reality, low, ocd, feels like, right, world, dp, scared, dissociation]"
1,0,87,"[weed, high, started, pretty, went, school, ago, panic attack, days, panic]"
2,1,84,"[like im, sleep, panic, attack, panic attack, night, wasnt, fucking, tired, panic attacks]"
3,2,60,"[therapy, post, finally, enjoy, friends, school, lost, lot, family, making]"
4,3,60,"[memory, memories, remember, self, reality, dreams, moment, forget, isnt, wrong]"
5,4,50,"[tried, supplements, medication, helps, taking, effect, thanks, sub, deep, safe]"
6,5,46,"[room, study, research, open, link, awareness, visual, looks, dark, vision]"
7,6,45,"[pressure, head, breathing, happen, weird, small, sleep, related, fog, visual]"
8,7,40,"[sub, posts, life felt, felt like, know dpdr, symptom, guess, disorder, gonna, stuff]"
9,8,38,"[blank, human, want, don know, lost, happy, realize, living, christmas, kind]"
10,9,35,"[conscious, inside, seeing, trapped, talking, makes feel, consciousness, world, surroundings, elses]"
11,10,34,"[existential, death, ocd, believe, exist, true, end, thoughts, different, fake]"
12,11,27,"[derealization, dreaming, depersonalization, derealisation, study, treatment, disorder, episodes, didn, antidepressants]"
13,12,19,"[dose, panic, effects, psychiatrist, worsening, long term, improved, depression, depersonalization, physically]"
14,13,14,"[trust, getting worse, mild, physical, work, worse, nearly, job, safe, didnt]"

In [12]:
# Look at examples per topic
#df["topic"] = topics #topics is only temporary output, so I need to create a column that is not temporary to inspect the element
df[df["topic"] == 13][["title", "text"]].head(10) #use number from "topic" column (instead of leftmost column)

KeyError: 'Topic'

In [14]:
df = pd.read_csv("dpdr_topics_sortiert.csv", encoding="utf-8", encoding_errors="replace")

In [24]:
# Try different code so that I can read the posts better
for post in df[df["topic"] == 12]["document"].head(15):
    print(post)
    print("\n" + "-"*100 + "\n")

It used to scare me (just a little rant). Having DPDR used to scare me , Id be terrified to move out of bed , I couldnt even look at a family member with out freaking out now its like all that fear anxiety has gone away. But not in a healing way in a way its been pushed down further nothing fazes me anymore. Its like Im stuck in some weird world and healing is going to take a hell of a lot of work time and effort. DPDR /dissociation has saved my life in many ways because I dont no what Id do if I was feeling right now so I thank that part of me but I also want that part to no Im safe now and Im capable of healing

----------------------------------------------------------------------------------------------------

Hopeless Ive had chronic dpdr since 2019 but in 2023 I worked a warehouse job for a week because my dpdr was getting worse, I quit the job felt fine, fast forward two months and out of nowhere my dpdr got worse, Ive been in this worsened state of dpdr for almost two years now, havent left the house in almost two years, I dont have a job and its very difficult to go outside the house. This is just unfair, Im literally in hell , just suffering everyday, fuck this disorder, shit makes no sense

----------------------------------------------------------------------------------------------------

IT GETS BETTER Keep on pushing. I know it sucks, its scary, DPDR completely halted my life - but thank god. Coming out of this I have SO MUCH JOY, so much more appreciation and love for the mundane. I cant remember much of the last year, and I still am under chronic DPDR, but within it the body and mind is so resilient. This is your brain protecting you, trust it! Trust your body - when you feel fear, anxiety, anything; MOVE!!! Wiggle your arms, jump around, rub your fingers together- MOTION WILL GROUND YOU! Only you can save yourself my friend. Keep pushing, I promise. If you look you can see my obsession with this forum, I spent weeks of my life scrolling- wanting to just disappear to get away from the feeling. Learn where anxiety settles in your body, learn how to get out that access energy, accept it. I recently have been struggling with my DPDR getting worse, I was forgetting dates, the time, everything - but I kept moving my life forward and my mind is finally starting to catch up with the world im building around me. I joined a local magazine during this episode, and today was the first time I interviewed someone for it! My friend (for context, we got close when she disclosed she deals with really bad OCD and depersonalization) and I both ran the interview, it went great, and after we both laughed about how insanely out of body we felt and how intense the depersonalization felt during the conversation- however we both continued, pushed everything into being present and afterwards could even laugh so hard about how ridiculous the depersonalization felt that we were in tears. It isnt this big monster, its you - protecting you!!! Have a great new years everyone

----------------------------------------------------------------------------------------------------

I have been diagnosed with DPDR So recently, Ive had a bit of a stressful month. I was recently diagnosed with DPDR/ MDD. Its been a brutal first week dealing with the disassociation and desensitization. To the point where its making it a challenge to do my everyday tasks. I cant even take care for myself properly, as everything feels like Im living in a simulation. Its been impossible to keep more than 1 thing in my head. Im pacing around at night with heavy panic attacks. How do you guys deal with your DPDR? What grounds you back into reality? If you had DPDR, does it go away? Will I feel like this forever? Its been absolute hell, and Id like to be able to communicate with someone who has went through the same thing. Thank you all in advance, as this is my first ever Reddit post

----------------------------------------------------------------------------------------------------

I had horrific, constant dpdr for years that is now nearly 100% cured: my story to those who need it This is sort of a long read, but if youre in a bad place and finding your dpdr is strongly affecting your functionality and quality of life please read this.As the title says: from 2021-2024 I had consistent episodes of dpdr and anxiety that would sometimes last for months. The worst of these episodes would leave me nearly non-functional and agoraphobic. I would absolutely dread leaving the house, and was barely able to function at work or school due to my condition. It was on my mind constantly and caused bizzare, ocd-like behaviors that manifested as a result of the horrific anxiety and stress I was constantly under.One thing I learned as that even if it doesnt feel like it, it always gets better. Sometimes even without any intervention. Another thing is that there is probably a lot more of a physical component to dpdr than it seems, and if youre in an already fragile mental state a physical issue can cause a seed that turns into a months-long spiral of feeling completely unreal and outside of your body. My episodes would always be at their worst in the winter, and the worst one of these episodes happened after I had moved away from home to an unfamiliar place in a dry, high-elevation climate. This also didnt do me any favors, I suspect that the lack of sunlight and pressure changes during winter can exacerbate symptoms to the extreme, similar to how they exacerbate things like migraines (which are also sometimes linked to dpdr)After this episode started to get better in the warmer months, I decided to dig into any physical causes that could be the source of my condition, after hearing about a myriad of physical issues that are linked to dpdr. I got all of my vitamins/hormones tested including vitamins D, B12, iron, testosterone, and many more, and found no abnormalities outside of a very slight vitamin D deficiency. That summer I saw something interesting: vertical heterophoria, a very slight vertical misalignment of the eyes, can cause dpdr due to the brain receiving a very slight misrepresentation of the world and having to compensate. Ive always had eye issues since birth but didnt see anything like this in my chart, so I scheduled a visit with my eye doctor, who casually mentioned that I actually do have this.All of a sudden, it felt like a gigantic weight was lifted off my shoulders. My dpdr episodes would always start with a bizzare, pressure-like sensation in the front of my head, but I had gotten an mri which confirmed no direct physical causes (like swelling, fluid buildup, or tumors) of this issue. I now realized the source was my eye misalignment, which was genuinely a casual side note that the doctors didnt even find important enough to put in my medical chart. Im now pretty confident that this acted like a seed that caused me to spiral from an already fragile mental state. The heterophobia caused very mild dpdr, which I hyperfixated on and caused it to get worse and worse until it was so severe I was minimally functional. This lined up exactly with my timeline of symptoms, and since learning I had vertical heterophoria Ive had barely any dpdr symptoms except for the initial pressure sensation, which is quite strong sometimes, and the very mild dpdr symptoms that come with it, which Ive been able to completely ignore and thus go away quick.Knowing about the cause of my issues was enough to nearly completely cure my dpdr and Ive been completely, 100% functional in school and work even through the winter. Its been over a year since I discovered this and I havent had a bad episode since. Its been genuinely life-changing for me.If youre in the same boat as me and dont know whats wrong, consider physical causes of your dpdr and know that simply a lack of knowing the physical cause can cause a spiral that feels extreme. I dont know who needs to read this, but just know it ALWAYS will get better.

----------------------------------------------------------------------------------------------------

IRL Cheat Code If youre struggling with fears induced by dpdr (especially the existential ones), losing weight helps. It is basically like taking beta blocker since losing weight means your heart doesnt have to beat as fast to supply your body with oxygen via blood. When you get adequate blood flow and oxygen this reassures your body that you are safe and activates the parasympathetic nervous system which quite literally promotes a sense of calmnessBut from experience dont push yourself too hard when you start. By this, I mean dont do anything that will cause your heart rate to spike. And yes I completely understand that things dont feel right. But a good exercise is walking because it distracts you and is efficient at burning calories. As long as a caloric surplus is maintained you will lose weightI say trust the science and I wish I knew this much earlier. I felt so helpless at the start but this is one thing you can physically do to improve your situation and give you control

----------------------------------------------------------------------------------------------------

scared of death (death anxiety) how do you cope with the fear of death? for me its literally that which Im scared of dpdr fading away from reality completely.

----------------------------------------------------------------------------------------------------

been experiencing dpdr for 3/4 years now, should i get help/how for context i live in the uk, ive been experiencing extreme dpdr symptoms for years now, sometimes i get so bad my vision goes hella tunnelvision, resolution and frame rate drops, sizing of different objects gets fucked( like things apear way bigger or smaller or further or closer), when symptoms higten i stumble and fall, hallucinating is extremely frequent, passing out, being near things like drugs/alcohol makes symptoms 10x worse, i just turned 18 and i live in scotland, if anyone can point me somewhere without bs year long waits i pleed

----------------------------------------------------------------------------------------------------

im SO tired of it Ive been doing the best I can to push myself a bit. stayed around with family and friends throughout the whole Super Bowl, go in the kitchen often to do things (sounds silly but for some reason my dpdr and anxiety is worse in there), just sticking through things in general despite feeling strong dpdr. today I woke up, stayed laying down for a bit and after about an hr I got up, made eggs and bacon sat to eat, decided I wanted to try ketchup with my eggs bc my friend always says how she loves it. I get up to get it and woah. Huge wave of all the symptoms of dpdr. I felt so stuck and frozen in that moment. still, I sat down ate, then went to the couch which rn is my safe spot but still, why?? like why. Ive been trying so hard to still do things and not think about it and it just comes up so randomly its so frustrating. also started lamtical two weeks ago to see if that works for me. im so nervous it wont and if it doesnt I dont have many options left to try. ugh so tiring. just had to rant.

----------------------------------------------------------------------------------------------------

Im going to be honest with you, the better you are at mindfulness and actually exercising the faster this will go away. Theres great number of you who say I dont have anxiety yet I still have dpdr, your dpdr makes you unaware of your anxiety and stress. It still affects you. Check how tense your body is.

----------------------------------------------------------------------------------------------------

Depersonalization/Derealization with panic at home When Im out in the outside world, I can manage my DPDR, but in my own home I cant handle it and I panic. (This is where my LSD bad trip happened.) How do you think I could overcome this? I constantly feel like Ive already lived my life and Im repeating it over and over again, reliving the mistakes near the end, and that Im uncontrollably approaching a reset. Thank you if you respond.

----------------------------------------------------------------------------------------------------

How do you know its going away? Ive had dpdr for over a year now. I really cant tell if its going away slowly. My anxiety from the onset of my dpdr has decreased drastically thanks to lexapro and Ive moved on with life. Im doing all the right things such as staying healthy and keeping myself distracted with work, hobbies and relationships. My mindset has changed for the better and I feel optimistic. But I feel like my physical symptoms havent changed a bit. The world still looks the same to me as the start of it. I feel overall better mentally but its like& still always there. It feels stuck. Either that or its a painfully gradual process. I know going on reddit doesnt help but this is a rare occasion for me.Anyway, what are some moments youve had when youve realised oh, it is actually going away?

----------------------------------------------------------------------------------------------------

After 9 years of worsening DPDR, I just want to know what happened If you're new to DPDR or if you're in a rough patch with your symptoms, I would encourage you to not read my story, as it could make you feel more hopeless, and I believe there is a lot of hope for pretty much everyone with this disorder. When I first got DPDR, it was very mild. Just a very slight feeling of being off, but nothing that was life-ruining in itself. I still felt real and like things around me were real. It was so mild that it barely even changed my life apart from the fact that I knew that something was going wrong, and that was of course scary. After around 4 months of very mild DPDR, it started getting worse and has never stopped since. Week after week, month after month, year after year it has gotten worse and worse to the point where I now feel completely gone with off the charts levels of DPDR and anhedonia, and it still hasn't stopped getting worse even after 9 years...I know it sounds absolutely unbelievable, and I can't even comprehend how it's possible myself. I can tell that the people closest to me have a hard time believing it, but I gain nothing from lying about it. I am not looking for pity. I just want to know what the hell happened, you know... It seems that most people either get very bad DPDR to start out with, and then slowly get better, or they have a baseline-level of DPDR, from where they have better and worse periods, but they always return to baseline. I know that every experience with heavy dissociation is painful, and I am not trying to minimize anyone's experience at all. I just don't understand why my condition has been progressive without a solid baseline. I know that I haven't treated myself too well, but it's still not normal to keep getting worse over such a long period of time. I don't know what to do about it. I have tried quite a lot of things in the past, but these past couple of years I kinda gave up and just hoped that I would eventually hit the bottom of the symptoms, so that I could start getting better or at least stop getting worse, but I don't think there is a bottom to the symptoms anymore. Quite frankly, I am scared of where this might end up, even if I can't feel that fear completely. I had brain scans done in the past, and I have gotten blood work done as well, but I might get some comprehensive blood work done again, because it's hard to believe that there isn't anything physically wrong with my system. I've also tried most of the common types of trauma therapy, metacognitive therapy, CBT, including other things like a couple of supplements, some meds, exercise, and all of the typical advice etc. I don't know what to do, and I'm feeling very hopeless. I guess I'm just hoping for a miracle. If you read this far, thank you very much, and I wish you all the best.

----------------------------------------------------------------------------------------------------


In [13]:
# Inspect single posts further
print(df.loc[181, "document"])

Blank mind mixed with some kind of anxiety I function, Im funny, functional human but when I am alone all kind of bad thoughts get me that my mind become blank. Its like I don't have anything in my mind. Im going to kill myself what have I done with myself. Im 34 and having this, im also lost. I had some problems mostly with panic attacks and anxiety but now blank mind is the biggest problem. I don't know where to go in my life cause i don't have a goal at all. Maybe just to be funny guy and that's it but I don't know who I am. Its like im nobody with a blank mind. That's the worst

Quite a lot of outliers. Can we reduce them?

In [17]:
#new_topics = topic_model.reduce_outliers(docs, topics)
#After runninng this, there was only 1 outlier left. Not good.

In [18]:
# Update the model
#topic_model.update_topics(docs, topics=new_topics)

In [19]:
# What does the new model look like?
#topic_model.get_topic_info()

Save the Model

In [4]:
# Save the model
#topic_model.save("bertopic_model", serialization="safetensors", save_ctfidf=True)
# Load later with:
from bertopic import BERTopic
topic_model = BERTopic.load("bertopic_model")

# WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

2026-08-30 20:43:23,426 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

Adjust the Number of Topics

In [21]:
# That is a lot of topics. See if I can reduce it
#new_topics = topic_model.reduce_outliers(
#    df["document"].tolist(),
#    topics,
#    strategy="embeddings"
#)

#topic_model.update_topics(df["document"].tolist(), topics=new_topics)

In [22]:
#topic_model = BERTopic.load("bertopic_model", embedding_model="all-MiniLM-L6-v2") # reload the model
#new_topics = topic_model.reduce_outliers(docs, topics, probabilities=probs, strategy="probabilities", threshold=0.05)
#topic_model.update_topics(docs, topics=new_topics)
#topic_model.reduce_topics(docs, nr_topics="auto")

In [23]:
# Let's see what happened
#topic_info = topic_model.get_topic_info()
#print(topic_info)
#The stopword list got ignored help

In [24]:
# Website with cool stuff
# https://maartengr.github.io/BERTopic/api/plotting/topics.html#bertopic.plotting._topics.visualize_topics

Visualise the Data

In [5]:
topic_model.set_topic_labels({-1: "Outliers",
                              0: "Substance Use",
                              1: "Panic & Health Anxiety",
                              2: "Therapeutic & Social Support",
                              3: "Discussing Symptoms #1",
                              4: "Treatment",
                              5: "Discussing Symptoms #2",
                              6: "Physical & Sensory Symptoms",
                              7: "Living with DPDR",
                              8: "Hopelessness",
                              9: "Discussing Symptoms #3",
                              10: "Existential Concerns",
                              11: "Diverse (Causes & Symptom Fluctuation)",
                              12: "Medication Experiences",
                              13: "Diverse (Symptoms & Recovery)"
                              })

In [26]:
# Intertopic distance map
fig = topic_model.visualize_topics(custom_labels=True)

# Show figure in notebook
fig.show()

In [27]:
# Save as html
#fig.write_html("new_bertopic_intertopic_distance_map.html")

Download the Data

In [28]:
# Download data
#df["topic"] = topics
#df["probs"] = probs.max(axis=1)  # save the highest probability per document
#df.to_csv("dpdr_topics.csv", index=False)

In [29]:
# Download the topic_info table
#topic_info = topic_model.get_topic_info()
#topic_info.to_csv("dpdr_topic_overview.csv", index=False)

In [30]:
#For when I want to reload the dataset without rerunning BERTopic
#df = pd.read_csv("dpdr_topics.csv")

In [31]:
print("The code worked, I think")

The code worked, I think

Finished this step!!